---
title: "Post #1"
description: "Personal goals for E155"
author: "Shreya Jampana"
date: "8/29/25"
draft: false
---

This semester, my personal goal in E-155 is to bridge a gap in my skill set: while I’ve always been drawn to analog circuitry and PCB design, I want to grow more confident in the digital side of hardware. I’m excited by the wide applications of embedded systems, from everyday devices to specialized applications in medicine and beyond, and I see this class as a chance to reframe how I think about hardware and software working together. I also want to get better at debugging with discipline rather than just trial and error. Another goal is to practice designing at the system level, balancing elegance with practicality, and then clearly communicating those decisions in reports and documentation. More broadly, I want to get comfortable with iteration and failure as part of the process, and to use the labs and project to experiment creatively and push myself beyond the bare minimum. After the labs and by the end of the semester, I hope to feel fluent enough in digital design to integrate it with my analog interests, and to carry that confidence into a really cool final project and beyond!
